<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\Setting;

class SettingsTableSeeder extends Seeder
{
    public function run(){

        DB::table('settings')->insert([ 'id' =>  '5', 'key' => 'admin.bg_image',                    'display_name' => 'Admin Background Image',                                 'value' => '',                                                  'details' => '', 'type' => 'image',     'order' => '5', 'group' => 'Admin' ]);
        DB::table('settings')->insert([ 'id' =>  '7', 'key' => 'admin.description',                 'display_name' => 'Admin Description',                                      'value' => 'Welcome to Voyager. The Missing Admin for Laravel', 'details' => '', 'type' => 'text',      'order' => '2', 'group' => 'Admin' ]);
        DB::table('settings')->insert([ 'id' =>  '9', 'key' => 'admin.icon_image',                  'display_name' => 'Admin Icon Image',                                       'value' => '',                                                  'details' => '', 'type' => 'image',     'order' => '4', 'group' => 'Admin' ]);
        DB::table('settings')->insert([ 'id' =>  '4', 'key' => 'ite.google_analytics_tracking_id',  'display_name' => 'Google Analytics Tracking ID',                           'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '4', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' =>  '6', 'key' => 'admin.title',                       'display_name' => 'Admin Title',                                            'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '1', 'group' => 'Admin' ]);
        DB::table('settings')->insert([ 'id' => '10', 'key' => 'admin.google_analytics_client_id',  'display_name' => 'Google Analytics Client ID (used for admin dashboard)',  'value' => 'text',                                              'details' => '', 'type' => '',          'order' => '1', 'group' => 'Admin' ]);
        DB::table('settings')->insert([ 'id' => '11', 'key' => 'site.twitter_card',                 'display_name' => 'twitter card',                                           'value' => 'summary',                                           'details' => '', 'type' => 'text',      'order' => '6', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '14', 'key' => 'site.news_description',             'display_name' => 'news description',                                       'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '9', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '15', 'key' => 'site.news_keywords',                'display_name' => 'news keywords',                                          'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '10', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '16', 'key' => 'site.news_image',                   'display_name' => 'news image',                                             'value' => '',                                                  'details' => '', 'type' => 'file',      'order' => '11', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '31', 'key' => 'site.footerCol3',                   'display_name' => 'Подвал колонка 3',                                       'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '25', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '18', 'key' => 'site.main_page_title',              'display_name' => 'main page title',                                        'value' => 'Главная',                                           'details' => '', 'type' => 'text',      'order' => '13', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '32', 'key' => 'site.footerCol4',                   'display_name' => 'Подвал колонка 4',                                       'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '26', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '33', 'key' => 'site.siteStart',                    'display_name' => 'Дата старта проекта',                                    'value' => '2019',                                              'details' => '', 'type' => 'text',      'order' => '27', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '19', 'key' => 'site.analytics',                    'display_name' => 'analytics',                                              'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '14', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '34', 'key' => 'site.siteAddress',                  'display_name' => 'Адрес (в подвале',                                       'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '28', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '21', 'key' => 'site.menuItems',                    'display_name' => 'menu items',                                             'value' => '3',                                                 'details' => '', 'type' => 'text',      'order' => '16', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '23', 'key' => 'site.site_seo_end_title',           'display_name' => 'site seo end title',                                     'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '17', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '24', 'key' => 'site.scrollDistance',               'display_name' => 'Число пикселей для подгрузки нового контента',           'value' => '200',                                               'details' => '', 'type' => 'text',      'order' => '19', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '25', 'key' => 'site.AjaxDuration',                 'display_name' => 'Время анимации подъема наверх страницы после ajax',      'value' => '500',                                               'details' => '', 'type' => 'text',      'order' => '20', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '26', 'key' => 'site.onEachSide',                   'display_name' => 'Кнопок пагинации',                                       'value' => '5',                                                 'details' => '', 'type' => 'text',      'order' => '21', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '27', 'key' => 'site.new_page',                     'display_name' => 'Адрес страницы ленты новостей',                          'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '22', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '29', 'key' => 'site.footerCol1',                   'display_name' => 'Подвал колонка 1',                                       'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '23', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '30', 'key' => 'site.footerCol2',                   'display_name' => 'Подвал колонка 2',                                       'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '24', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '35', 'key' => 'site.siteCopyright',                'display_name' => 'Копирайт',                                               'value' => 'Все права защищены',                                'details' => '', 'type' => 'text',      'order' => '29', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '45', 'key' => 'site.newsChangefreq',               'display_name' => 'Частота обновления страницы новостей в сайтмапе	daily', 'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '39', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '36', 'key' => 'site.crossLimit',                   'display_name' => 'Число популярных в посте',                               'value' => '3',                                                 'details' => '', 'type' => 'text',      'order' => '30', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '37', 'key' => 'site.newCrossLimit',                'display_name' => 'Новинок из категории в посте',                           'value' => '3',                                                 'details' => '', 'type' => 'text',      'order' => '31', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '38', 'key' => 'site.crossTextLenth',               'display_name' => 'Длина текста в превью кросс записи',                     'value' => '50',                                                'details' => '', 'type' => 'text',      'order' => '32', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '39', 'key' => 'site.hotPostsDays',                 'display_name' => 'Сколько дней пост считается горячим',                    'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '33', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '40', 'key' => 'site.socialsButtons',               'display_name' => 'Кнопки поделиться в записях и страницах',                'value' => '1',                                                 'details' => '', 'type' => 'checkbox',  'order' => '34', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '42', 'key' => 'site.mainPageId',                   'display_name' => 'Id главной страницы',                                    'value' => '1',                                                 'details' => '', 'type' => 'text',      'order' => '36', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '44', 'key' => 'site.searchTextDescription',        'display_name' => 'Текст подсказки поиска',                                 'value' => 'Вы ищете',                                          'details' => '', 'type' => 'text',      'order' => '38', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '2', 'key' => 'site.description',                   'display_name' => 'Site Description',                                       'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '2', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '12', 'key' => 'site.twitter_site',                 'display_name' => 'twitter site',                                           'value' => '',                                                  'details' => '', 'type' => 'text',      'order' => '7', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '20', 'key' => 'site.ableLastModified',             'display_name' => 'Table LastModified',                                     'value' => '1',                                                 'details' => '', 'type' => 'checkbox',  'order' => '15', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '48', 'key' => 'site.headerSctipts',                'display_name' => 'код в header',                                           'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '42', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '43', 'key' => 'site.videoCategoryId',              'display_name' => 'id категории с видео для главной',                       'value' => '2',                                                 'details' => '', 'type' => 'text',      'order' => '37', 'group' => '' ]);
        DB::table('settings')->insert([ 'id' => '8', 'key' => 'admin.loader',                       'display_name' => 'Admin Loader',                                           'value' => '',                                                  'details' => '', 'type' => 'image',     'order' => '3', 'group' => '' ]);
        DB::table('settings')->insert([ 'id' => '47', 'key' => 'site.robots',                       'display_name' => 'Содержимое robots.txt',                                  'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '41', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '51', 'key' => 'site.allowComments',                'display_name' => 'Разрешить комментарии',                                  'value' => '1',                                                 'details' => '', 'type' => 'checkbox',  'order' => '45', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '46', 'key' => 'site.sitemapLinks',                 'display_name' => 'Число ссылок в одном файле sitemap',                     'value' => '500',                                               'details' => '', 'type' => 'text',      'order' => '40', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '17', 'key' => 'site.news_on_page',                 'display_name' => 'news on page',                                           'value' => '6',                                                 'details' => '', 'type' => 'text',      'order' => '12', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '52', 'key' => 'site.categories_on_page',           'display_name' => 'Категорий на странице',                                  'value' => '10',                                                'details' => '', 'type' => 'text',      'order' => '46', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '3', 'key' => 'site.logo',                          'display_name' => 'Site Logo',                                              'value' => '',                                                  'details' => '', 'type' => 'image',     'order' => '3', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '50', 'key' => 'site.disquslink',                   'display_name' => 'Путь до js файла комментирования',                       'value' => 'tokio-2',                                           'details' => '', 'type' => 'text',      'order' => '44', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '54', 'key' => 'site.logoWhite',                    'display_name' => 'Инвертированный логотип',                                'value' => '',                                                  'details' => '', 'type' => 'image',     'order' => '49', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '41', 'key' => 'site.sitebarAd',                    'display_name' => 'Блок рекламы в правой колонке',                          'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '35', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '55', 'key' => 'site.generalizeCategoryId',         'display_name' => 'Id обобщающей категории',                                'value' => '9',                                                 'details' => '', 'type' => 'text',      'order' => '50', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '56', 'key' => 'site.turboMenu',                    'display_name' => 'ссылки в турбо версии',                                  'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '51', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '22', 'key' => 'site.socials',                      'display_name' => 'socials',                                                'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '18', 'group' => 'Site' ]);
        DB::table('settings')->insert([ 'id' => '49', 'key' => 'site.footerSctipts',                'display_name' => 'код в hfooter',                                          'value' => '',                                                  'details' => '', 'type' => 'text_area', 'order' => '43', 'group' => 'Site' ]);
    }
}
